# -*- coding: utf-8 -*-
"""Kelompok15_IF-44-GAB02_Tubes Revisi Statistika.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HzBPooz58zX7HMiTXKY57gqr_6Jksz7q

<Center>
<h1><b>TUGAS BESAR STATISTIKA</b></h1>
<div>
<b>Kelompok 15:</b><br>
Aidil Arifin Nizar - 1301204180<br>
Dufha Arista - 1301204156<br>
Muhammad Faras Daffa - 1301204186<br>
<br><br>
</div>
</center>

**1. Tujuan**

> Mahasiswa mampu menerapkan metode-metode deskripsi data, pengolahan dan analisis data   (kategorik maupun kuantitatif)  untuk menyelesaikan masalah  keteknikan dengan prinsip-prinsip computing

**2. Uraian Tugas**

>Mengeksplor data suatu bank mengapa pelanggan ada yang berpindah ke bank lain

# Menginstall Packages dan Menggunakan Library
"""

install.packages("ggplot2") # to plot
install.packages("gridExtra") # to grid plot
install.packages("dplyr") # grammar of data manipulation
install.packages("tidyverse") # data manipulation
install.packages("cowplot") # add-on plot for ggplot
install.packages("breakDown") # binary classifiers and general regression models
install.packages("ggthemes") # tol get additional plot themes
install.packages("corrplot") # graphical display of a correlation matrix
library(corrplot)
library(breakDown)
library(ggthemes)
library(ggplot2)
library(scales)
library(dplyr)
library(tidyverse)
library(gridExtra)
library(cowplot)
library(tidyverse)
library(scales)

"""# Membaca Data csv"""

datacsv = read.csv('https://github.com/MuhammadFarrasDaffa/Statistika/blob/main/BankChurners.csv?raw=true')
new_datacsv = rename(datacsv, c("Naive_Bayes_Classifier1"="Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1", "Naive_Bayes_Classifier2"="Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2"))

"""Memasukkan file csv yang diunggah di github ke dalam R Colab"""

glimpse(new_datacsv)

"""Menampilkan jenis tipe data didalam csv"""

head(new_datacsv, 8)
tail(new_datacsv, 8)

"""Menampilkan Awal dan Akhir file csv"""

summary(new_datacsv)

"""Menampilkan rangkuman dari hasil data csv"""

sum(is.na(new_datacsv))

"""Mengetahui apakah ada data hilang yang terdapat di file csv

# Visualisasi data Attrition_Flag
"""

count_data <- datacsv %>%
  count(Attrition_Flag) %>%
  mutate(count = n/ sum(n), 
         count_label = paste0(round(count*100), "%"))
ggplot(count_data, aes(x = reorder(Attrition_Flag, -count), y = count)) +
  geom_bar(aes(fill = factor(Attrition_Flag)), stat = "identity", col = "black") +
  geom_text(aes(label = count_label), vjust = -0.25) +
  labs(x = "Status Pelanggan", y = "Frekuensi",
       title = "Status Pelanggan", fill = "Attrition Flag") +
  scale_y_continuous(labels = scales::percent) +
theme_economist()

"""Dari grafik batang diatas, maka hasil yang didapat:

*   Pelanggan yang tetap mendapatkan 84%
*   Pelanggan yang pindah mendapatkan 16%

Jadi, pelanggan yang tetap di bank tersebut lebih banyak dibandingkan dengan pelanggan yang keluar

# Visualisasi data Gender
"""

count_data <- datacsv %>%
  count(Gender)
ggplot(count_data, aes(x = reorder(Gender, n), y = n)) +
  geom_bar(aes(fill = Gender), stat = "identity", col = "black") +
  geom_text(aes(label = n), vjust = -0.25) +
  labs(x = "jenis kelamin", y = "frekuensi",
       title = "Banyaknya Jenis Kelamin", Fill = "Gender") +
  theme_wsj()

"""Dari grafik batang diatas, maka hasil yang didapat:

*   Jenis Kelamin Perempuan mendapatkan total 5358
*   Jenis Kelamin Laki-Laki mendapatkan total 4769

Jadi, jenis kelamin perempuan total lebih besar dibandingan dengan jenis kelamin laki-laki

# Visualisasi data Education_Level
"""

pct<- round(table(datacsv$Education_Level)/sum(table(datacsv$Education_Level))*100)
pie(table(datacsv$Education_Level),main = "Perbandingan Tingkat Pendidikan Pelanggan")
pct

"""Dari diagram lingkaran diatas, maka:

*   Mahasiswa/I mendapatkan 10%
*   Doktor mendapatkan 4%
*   Sarjana mendapatkan 31%
*   Pelajar SMA mendapatkan 20%
*   Pasca Sarjana mendapatkan 5%   
*   Tidak Berpendidikan mendapatkan 15%
*   Tidak Diketahui mendapatkan 15%

Jadi, dapat kita simpulkan bahwa Sarjana merupakan tingkat pendidikan pelanggan paling tinggi dan Doktor merupakan tingkat pendidikan pelanggan paling rendah

# Visualisasi data Customer_Age
"""

ggplot(datacsv, aes(x = Customer_Age)) +
  geom_histogram(aes(fill = factor(Customer_Age)), binwidth = 5, col = "black", alpha = 1 ) +
  labs(y = "Banyaknya",
       x = "Umur",
       title = "Umur Pelanggan", fill = "Customer Age") +
geom_vline(aes(xintercept = mean(Customer_Age, na.rm = T), color = "mean"), show.legend = T, size = 2) +
geom_vline(aes(xintercept = median(Customer_Age, na.rm = T), color = "median"), show.legend = T) +
scale_color_manual(name = "Statistics", values = c(mean = "gold", median = "black")) +
theme_foundation(base_size = 11, base_family = "sans")
mean(datacsv$Customer_Age)
median(datacsv$Customer_Age)

"""Dari histogram diatas, maka:

*   Umur Pelanggan terbanyak adalah 46 tahun
*   Umur Pelanggan tersedikit adalah 26 tahun

---
Kemudian, rata-rata dan nilai tengah yang terdapat di histogram diatas adalah

> Mean = 46.3259603041375
>
> Median = 46

# Visualisasi data Marital Status
"""

pct<- round(table(datacsv$Marital_Status)/sum(table(datacsv$Marital_Status))*100)
pie(table(datacsv$Marital_Status),main = "Perbandingan Tingkat Status Pernikahan Pelanggan")
pct

"""Dari diagram lingkaran diatas, maka:

*   Cerai mendapatkan 7%
*   Menikah mendapatkan 46%
*   Lajang mendapatkan 39%
*   Tidak diketahui mendapatkan 7%

Jadi, dapat kita simpulkan bahwa status pernikahan pelanggan banyak terdapat di Menikah dan sedikit terdapat di tidak diketahui dan bercerai

# Visualisasi data Total_Relationship_Count
"""

hist(datacsv$Total_Relationship_Count, freq = F, ylim = c(0, 0.5), breaks = 8,
     main = "Jumlah Hubungan Total", xlab = "Jumlah total produk yang dipegang oleh pelanggan",
     ylab = "Rasio", las = 1, col = "beige")
lines(density(datacsv$Total_Relationship_Count), col = "blue", lwd = 3)

"""Dari histogram diatas, maka:

*   Jumlah total produk yang dipegang oleh pelanggan paling tinggi adalah 3
*   Jumlah total produk yang dipegang oleh pelanggan paling rendah adalah 1

# Visualisasi Data Card_Category
"""

count_data <- datacsv %>%
  count(Card_Category)
ggplot(count_data, aes(x = reorder(Card_Category, n), y = n)) +
  geom_bar(aes(fill = factor(Card_Category)), stat = "identity", col = "black") +
  geom_text(aes(label = n), vjust = -0.25) +
  labs(x = "kategori kartu", y = "frekuensi",
       title = "Banyaknya kategori kartu yang dipakai pelanggan", fill = " Card Category") +
  theme_fivethirtyeight()

"""Dari diagram batang diatas, maka:

*   Kategori kartu terbanyak dipegang oleh Blue dengan total 9436
*   Kategori kartu tersedikit dipegang oleh Platinum dengan total 20

# Visualisasi Data Income_Category
"""

count_data <- datacsv %>%
  count(Income_Category) %>%
  mutate(count = n/ sum(n), 
         count_label = paste0(round(count*100), "%"))
ggplot(count_data, aes(x = reorder(Income_Category, -count), y = count)) +
  geom_bar(aes(fill = factor(Income_Category)), stat = "identity", col = "black") +
  geom_text(aes(label = count_label), vjust = -0.25) +
  labs(x = "Kategori", y = "Frekuensi",
       title = "Pendapatan Pelanggan", fill = "Income Category") +
  scale_y_continuous(labels = scales::percent) +  
  theme_excel()

"""Dari diagram batang diatas, maka:

*   Pendapatan pelanggan paling banyak adalah kurang dari 40k Dollar dengan 35%
*   Pendapatan pelanggan paling sedikit adalah 120k Dollar lebih dari dengan 7%

# Membandingkan data

Membandingkan data Gender dengan Attrition_Flag
"""

ggplot(datacsv, aes(x = Gender, fill = Attrition_Flag)) +
  theme_bw() +
  geom_bar(col = "black") +
  labs(y = "Frekuensi",
       title = "Perbandingan Status Pelanggan dengan jenis kelamin", fill = "Attrition Flag")

"""Dari grafik batang diatas, maka kesimpulan yang dapat kita ambil:

*   Untuk jenis kelamin perempuan status pelanggan yang pindah lebih banyak dibandingkan dengan laki-laki.
*   Untuk jenis kelamin perempuan status pelanggan yang tetap lebih sedikit dibandingkan dengan laki-laki.

Membandingkan data Customer_Age dengan Attrition_Flag
"""

ggplot(datacsv, aes(x = Customer_Age, fill = Attrition_Flag)) +
  theme_bw() +
  geom_histogram(binwidth = 8, col = "black") +
  labs(y = "Frekuensi",
       x = "Age",
       title = "Perbandingan umur pelanggan dengan status pelanggan", fill = "Attrition Flag")

"""Dari grafik histogram diatas, maka:

---
Kesimpulan yang dapat kita ambil bahwa rentang umur pelanggan diantara 40-60  lebih banyak pelanggan yang pindah dan tetap

**Membandingkan 3 data (Attrition Flag, Gender, Customer Age)**
"""

ggplot(datacsv, aes(x = Gender, fill = Attrition_Flag)) +
  theme_bw() +
  facet_wrap(~ Customer_Age) +
  geom_bar() +
  labs(y = "Frekuensi",
       title = "Perbandingan 3 data", fill = "Attrition Flag")

"""dari grafik diatas, maka:

---
kesimpulan yang dapat kita ambil bahwa pelanggan perempuan tetap dan pindah terbanyak di umur 44 tahun dan pelanggan laki-laki terbanyak di umur 46 tahun

**Membandingkan data Education_Level dengan Attrition_Flag**
"""

ggplot(datacsv, aes(x = Education_Level, fill = Attrition_Flag)) +
  theme_bw() +
  geom_histogram(stat = "count", col = "black") +
  labs(y = "Frekuensi",
       x = "Age",
       title = "Perbandingan tingkat pendidikan pelanggan dengan status pelanggan", fill = "Attrition Flag")

"""dari grafik histogram diatas, maka:

---
* Pelanggan yang pindah dan tetap terbanyak di sarjana
* Pelanggan yang pindah dan tetap tersedikit di doktor

**Membandingkan data Card_Category dengan Attrition_Flag**
"""

ggplot(datacsv, aes(x = Card_Category, fill = Attrition_Flag)) +
  theme_bw() +
  geom_bar(alpha = 0.8, col = "black") +
  labs(y = "Frekuensi",
       x = "Kategori Kartu",
       title = "Perbandingan kategori kartu pelanggan dengan Status Pelanggan ", fill = "Attrition Flag")

"""dapat dilihat di grafik diatas tersebut, maka:

* Pelanggan tetap dan pindah paling banyak memiliki kartu Biru
* Pelanggan tetap dan pindah paling sedikit memiliki kartu Platimun

Membandingkan 3 data (Education_Level, Card_Category, dan Attrition_Flag)
"""

ggplot(datacsv, aes(x = Education_Level, fill = Attrition_Flag)) +
  theme_bw() +
  facet_wrap(~ Card_Category) +
  geom_histogram(stat = "count", position = "dodge") +
  labs(y = "Frekuensi",
       title = "Perbandingan 3 data", fill = "Attrition Flag")

"""dari grafik diatas, maka:

---
kesimpulan yang dapat kita ambil bahwa pelanggan tetap dan pindah paling banyak di tingkat pendidikan sarjana dan mereka banyak memiliki kartu berwarna biru

Membandingkan data Income_Category dengan Attrition_Flag
"""

ggplot(datacsv, aes(x = Income_Category, fill = Attrition_Flag)) +
  theme_bw() +
  geom_histogram(stat = "count", alpha = 0.8, col = "black") +
  labs(y = "Frekuensi",
       x = "Kategori Pendapatan",
       title = "Perbandingan pendapatan pelanggan dengan status pelanggan", fill = "Attrition Flag")

"""Dari grafik diatas, maka:
* pelanggan tetap dan pindah paling banyak memiliki pendapatan kurang dari 40k dollar.
* Pelanggan tetap dan pindah paling sedikit memilki pendapatan lebih dari 120k dollar.

Membandingkan data Marital_Status dengan Attrition_Flag
"""

ggplot(datacsv, aes(x = Marital_Status, fill = Attrition_Flag)) +
  theme_bw() +
  geom_bar(col = "black") +
  labs(x = "status pernikahan", y = "Frekuensi",
       title = "Perbandingan status pernikahan pelanggan dengan status pelanggan", fill = "Attirition Flag")

"""Dari grafk batang diatas, maka:
* Status pernikahan pelanggan tetap dan pindah paling banyak terdapat di menikah
* Status pernikahan pelanggan tetap dan pindah paling sedikit terdapat di tidak diketahui dan bercerai

Membandingkan 3 data (Marital_Status, Income_Category, dan Attrition_Flag)
"""

ggplot(datacsv, aes(x = Marital_Status, fill = Attrition_Flag)) +
  theme_bw() +
  facet_wrap(~ Income_Category) +
  geom_bar() +
  labs(x = "Status Pernikahan", y = "frekuensi",
       title = "Perbandingan 3 data", fill = "Attrition Flag")

"""dari grafik diatas, maka:

---
Kesimpulan yang dapat kita ambil bahwa pelanggan tetap dan pindah paling banyak di status menikah dan mereka banyak yang memiliki pendapatan kurang dari 40k dollar.

# Korelasi data
"""

kor <- datacsv %>% mutate_if(is.character, as.factor)

"""Mengubah jenis data Character menjadi Factor

**1. Mencari nilai korelasi Attrition_Flag dengan Gender melalui metode pearson**
"""

cor.test(as.numeric(kor$Attrition_Flag), as.numeric(kor$Gender), method = "pearson" )

"""*   Koefisien korelasi antara x dan y adalah 0.037  
*   p-valuenya 0.00017

---
**Kesimpulan yang dapat kita ambil bahwa kedua data tersebut terdapat korelasi**

**2. Mencari nilai korelasi Attrition_Flag dengan Customer_Age melalui metode pearson**
"""

cor.test(as.numeric(kor$Attrition_Flag), as.numeric(kor$Customer_Age), method = "pearson" )

"""* Koefisien korelasi antara x dan y adalah -0.018
* p-valuenya 0.066

---
**Kesimpulan yang dapat kita ambil bahwa kedua data tersebut terdapat korelasi**

**3. Mencari nilai korelasi Attrition_Flag dengan Marital_Status melalui metode pearson**
"""

cor.test(as.numeric(kor$Attrition_Flag), as.numeric(kor$Marital_Status), method = "pearson")

"""*   Koefisien korelasi antara x dan y adalah -0.019  
*   p-valuenya 0.039

---
**Kesimpulan yang dapat kita ambil bahwa kedua data tersebut terdapat korelasi**

**4. Mencari nilai korelasi Attrition_Flag dengan Card_Category melalui metode Pearson**
"""

cor.test(as.numeric(kor$Attrition_Flag), as.numeric(kor$Card_Category), method = "pearson" )

"""*   Koefisien korelasi antara x dan y adalah 0.0060  
*   p-valuenya 0.54

---
**Kesimpulan yang dapat kita ambil bahwa kedua data tersebut terdapat korelasi**

**5. Mencari nilai korelasi Attrition_Flag dengan Income_Category melalui metode pearson**
"""

cor.test(as.numeric(kor$Attrition_Flag ), as.numeric(kor$Income_Category), method = "pearson" )

"""*   Koefisien korelasi antara x dan y adalah -0.017  
*   p-valuenya 0.048

---
**Kesimpulan yang dapat kita ambil bahwa kedua data tersebut terdapat korelasi**

**6. Mencari nilai korelasi Attirition_Flag dengan Education_Level melalui metode pearson**
"""

cor.test(as.numeric(kor$Attrition_Flag), as.numeric(kor$Education_Level), method = "pearson" )

"""*   Koefisien korelasi antara x dan y adalah -0.0055  
*   p-valuenya 0.57

---
**Kesimpulan yang dapat kita ambil bahwa kedua data tersebut terdapat korelasi**

"""